---
# Network Configuration
- hosts: jumpbox
  roles:
   - network
   - keypair
   - security
   - flavor 
  tasks:

  - name: Create frontend instance
    include_role:
       name: instance
       vars_from: frontend.yml

  - name: Create app1 instance
    include_role:
       name: instance
       vars_from: app1.yml

  - name: Create app2 instance
    include_role:
       name: instance
       vars_from: app2.yml

  - name: Create db instance
    include_role:
       name: instance
       vars_from: db.yml

#  - name: Gather facts
#    include_role: 
#       name: osp-facts
#    tags:
#     - test_inventory
...
